import path from "node:path";
import { PrismaClient } from "@prisma/client";
import { PrismaBetterSQLite3 } from "@prisma/adapter-better-sqlite3";

/**
 * Database access.
 *
 * SQLite is reached through the official driver adapter, which pairs with the
 * WASM query compiler generated by `prisma generate` (engineType = "client").
 * That means no native engine binary is required — the same code path works on
 * a laptop, in CI and in a container.
 *
 * Every query in the application goes through Prisma; no module builds SQL by
 * string concatenation.
 */

/** Resolves `file:./prisma/dev.db` against the project root, not the cwd at call time. */
export function resolveDatabaseUrl(): string {
  const raw = process.env.DATABASE_URL?.trim() || "file:./prisma/dev.db";
  if (raw === ":memory:" || !raw.startsWith("file:")) return raw;
  const filePath = raw.replace(/^file:/, "");
  const absolute = path.isAbsolute(filePath) ? filePath : path.join(process.cwd(), filePath);
  return `file:${absolute}`;
}

const globalForPrisma = globalThis as unknown as { __phcPrisma?: PrismaClient };

function createPrismaClient() {
  const adapter = new PrismaBetterSQLite3({ url: resolveDatabaseUrl() });
  return new PrismaClient({
    adapter,
    // Never log query payloads: they contain medical data.
    log: process.env.NODE_ENV === "development" ? ["warn", "error"] : ["error"],
  });
}

export const prisma: PrismaClient = globalForPrisma.__phcPrisma ?? createPrismaClient();

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.__phcPrisma = prisma;
}

export type { PrismaClient };
