"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Camera, FileText, Loader2, Sparkles, UploadCloud, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { useI18n } from "@/components/providers/i18n-provider";
import { useActiveProfile } from "@/components/providers/profile-provider";
import { ErrorState } from "@/components/health/states";
import { uploadRecordAction } from "@/lib/actions/records";
import { formatBytes } from "@/lib/uploads/limits";
import { cn } from "@/lib/utils";

/** Samples let a judge (or a curious user) run the whole pipeline with no file. */
const SAMPLES = [
  { key: "prescription", labelKey: "recordType.PRESCRIPTION", emoji: "💊", title: "prescription" },
  { key: "blood-report", labelKey: "recordType.LAB_REPORT", emoji: "🧪", title: "blood-report" },
  { key: "lipid-profile", labelKey: "recordType.LAB_REPORT", emoji: "🫀", title: "lipid-profile" },
  { key: "diabetes-panel", labelKey: "recordType.LAB_REPORT", emoji: "🍬", title: "diabetes-panel" },
] as const;

const PIPELINE_STAGES = [
  "processing.uploading",
  "processing.reading",
  "processing.extracting",
  "processing.understanding",
  "processing.summarizing",
] as const;

type StageIndex = 0 | 1 | 2 | 3 | 4;

export function UploadDropzone() {
  const { t, easyRead } = useI18n();
  const { activeProfile } = useActiveProfile();
  const router = useRouter();

  const [file, setFile] = React.useState<File | null>(null);
  const [sampleKey, setSampleKey] = React.useState<string | null>(null);
  const [recordType, setRecordType] = React.useState<string>("AUTO");
  const [recordDate, setRecordDate] = React.useState<string>("");
  const [isDragging, setIsDragging] = React.useState(false);
  const [stage, setStage] = React.useState<StageIndex | null>(null);
  const [error, setError] = React.useState<string | null>(null);

  const fileInputRef = React.useRef<HTMLInputElement>(null);
  const cameraInputRef = React.useRef<HTMLInputElement>(null);
  const [isPending, startTransition] = React.useTransition();

  const maxMb = Number(process.env.NEXT_PUBLIC_MAX_UPLOAD_MB ?? 10);

  const acceptFile = (candidate: File | null) => {
    setError(null);
    if (!candidate) return;
    const allowed = /\.(jpe?g|png|webp|heic|heif|pdf)$/i.test(candidate.name) || candidate.type.startsWith("image/") || candidate.type === "application/pdf";
    if (!allowed) {
      setError(t("upload.invalidType"));
      return;
    }
    if (candidate.size > maxMb * 1024 * 1024) {
      setError(t("upload.tooLarge", { size: maxMb }));
      return;
    }
    setSampleKey(null);
    setFile(candidate);
  };

  /** Builds a tiny in-memory PDF so the demo sample needs no real file. */
  const makeSampleFile = (key: string): File => {
    const body = `%PHC-DEMO-SAMPLE:${key}\nDemo sample document generated by Personal Health Copilot.`;
    return new File([body], `sample-${key}-${activeProfile.name.replace(/\s+/g, "-").toLowerCase()}.pdf`, {
      type: "application/pdf",
    });
  };

  const runPipeline = (payloadFile: File, payloadSample: string | null) => {
    setError(null);
    setStage(0);

    // Realistic staged progress: never claim the document was understood instantly.
    const startedAt = Date.now();
    let currentStage: StageIndex = 0;
    const timer = window.setInterval(() => {
      currentStage = Math.min(4, currentStage + 1) as StageIndex;
      setStage(currentStage);
    }, 900);

    const formData = new FormData();
    formData.set("file", payloadFile);
    formData.set("profileId", activeProfile.id);
    if (payloadSample) formData.set("sampleKey", payloadSample);
    if (recordType !== "AUTO") formData.set("recordType", recordType);
    if (recordDate) formData.set("recordDate", recordDate);

    startTransition(async () => {
      const result = await uploadRecordAction({ ok: false }, formData);
      const elapsed = Date.now() - startedAt;
      // Let the last stage stay visible briefly so the pipeline feels honest.
      const remaining = Math.max(0, 3200 - elapsed);
      window.clearInterval(timer);
      await new Promise((resolve) => setTimeout(resolve, remaining));

      if (!result.ok || !result.recordId) {
        setStage(null);
        const message =
          result.error === "INVALID_TYPE"
            ? t("upload.invalidType")
            : result.error === "TOO_LARGE"
              ? t("upload.tooLarge", { size: maxMb })
              : result.error === "FORBIDDEN"
                ? t("error.forbidden")
                : t("error.ocrFailed");
        setError(message);
        return;
      }

      toast.success(t("processing.done"));
      setStage(4);
      router.push(`/records/${result.recordId}?review=1`);
    });
  };

  const handleSubmit = () => {
    if (!file && !sampleKey) {
      setError(t("upload.invalidType"));
      return;
    }
    const payloadFile = file ?? makeSampleFile(sampleKey ?? "blood-report");
    runPipeline(payloadFile, sampleKey);
  };

  // ── Processing state ─────────────────────────────────────────────────────
  if (stage !== null || isPending) {
    return (
      <Card aria-live="polite">
        <CardContent className="space-y-5 py-8">
          <div className="flex flex-col items-center gap-3 text-center">
            <span className="relative flex size-16 items-center justify-center rounded-full bg-brand-50">
              <span aria-hidden="true" className="absolute inset-0 animate-[pulse-ring_1.8s_ease-out_infinite] rounded-full bg-brand-200" />
              <Loader2 className="size-8 animate-spin text-brand-600" aria-hidden="true" />
            </span>
            <h2 className="text-xl font-semibold text-ink-900">{t("processing.title")}</h2>
            <p className="max-w-md text-sm text-muted">{t("processing.pleaseWait")}</p>
          </div>

          <Progress value={((stage ?? 0) + 1) * 20} aria-label={t("processing.title")} />

          <ol className="mx-auto max-w-md space-y-2.5">
            {PIPELINE_STAGES.map((stageKey, index) => {
              const state = (stage ?? 0) > index ? "done" : (stage ?? 0) === index ? "active" : "pending";
              return (
                <li key={stageKey} className="flex items-center gap-3">
                  <span
                    aria-hidden="true"
                    className={cn(
                      "flex size-8 shrink-0 items-center justify-center rounded-full text-sm font-semibold",
                      state === "done" && "bg-good-100 text-good-700",
                      state === "active" && "bg-brand-100 text-brand-700",
                      state === "pending" && "bg-ink-100 text-ink-400",
                    )}
                  >
                    {state === "done" ? "✓" : index + 1}
                  </span>
                  <span
                    className={cn(
                      "text-base",
                      state === "pending" ? "text-ink-400" : "text-ink-800",
                      state === "active" && "font-medium",
                    )}
                  >
                    {t(stageKey)}
                  </span>
                </li>
              );
            })}
          </ol>

          <p className="text-center text-xs text-muted">{t("upload.hintSize")}</p>
        </CardContent>
      </Card>
    );
  }

  // ── Upload form ──────────────────────────────────────────────────────────
  return (
    <div className="space-y-5">
      {error && (
        <ErrorState
          title={t("error.ocrFailed")}
          description={error}
          onRetry={() => {
            setError(null);
            setFile(null);
            setSampleKey(null);
          }}
          retryLabel={t("common.tryAgain")}
          secondaryLabel={t("common.uploadAnotherFile")}
          secondaryHref="/upload"
        />
      )}

      <Card>
        <CardContent className="space-y-4">
          <div
            onDragOver={(event) => {
              event.preventDefault();
              setIsDragging(true);
            }}
            onDragLeave={() => setIsDragging(false)}
            onDrop={(event) => {
              event.preventDefault();
              setIsDragging(false);
              acceptFile(event.dataTransfer.files?.[0] ?? null);
            }}
            className={cn(
              "flex flex-col items-center gap-3 rounded-2xl border-2 border-dashed p-6 text-center transition-colors sm:p-10",
              isDragging ? "border-brand-400 bg-brand-50" : "border-ink-300 bg-ink-50/40",
            )}
          >
            <span aria-hidden="true" className="text-4xl">
              📄
            </span>
            <p className="text-lg font-semibold text-ink-900">{t("upload.dropHere")}</p>
            <p className="text-sm text-muted">{t("upload.supported", { size: maxMb })}</p>

            <div className="mt-1 flex flex-wrap items-center justify-center gap-2">
              <Button type="button" variant="secondary" onClick={() => fileInputRef.current?.click()}>
                <UploadCloud aria-hidden="true" />
                {t("upload.chooseFile")}
              </Button>
              <Button type="button" variant="secondary" onClick={() => cameraInputRef.current?.click()}>
                <Camera aria-hidden="true" />
                {t("upload.useCamera")}
              </Button>
            </div>

            <input
              ref={fileInputRef}
              type="file"
              accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf"
              className="sr-only"
              aria-label={t("upload.chooseFile")}
              onChange={(event) => acceptFile(event.target.files?.[0] ?? null)}
            />
            <input
              ref={cameraInputRef}
              type="file"
              accept="image/*"
              capture="environment"
              className="sr-only"
              aria-label={t("upload.useCamera")}
              onChange={(event) => acceptFile(event.target.files?.[0] ?? null)}
            />

            <p className="text-xs text-muted a11y-hide">{t("upload.dropzoneHint")}</p>
          </div>

          {file && (
            <div className="flex items-center gap-3 rounded-2xl border border-brand-200 bg-brand-50 p-3">
              <FileText className="size-5 shrink-0 text-brand-700" aria-hidden="true" />
              <div className="min-w-0 flex-1">
                <p className="truncate font-medium text-ink-900">{file.name}</p>
                <p className="text-xs text-muted">
                  {t("upload.fileReady")} · {formatBytes(file.size)}
                </p>
              </div>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                aria-label={t("upload.removeFile")}
                onClick={() => setFile(null)}
              >
                <X aria-hidden="true" />
              </Button>
            </div>
          )}

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="recordType">{t("upload.recordType")}</Label>
              <Select value={recordType} onValueChange={setRecordType}>
                <SelectTrigger id="recordType">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="AUTO">{t("common.all")} — {t("review.documentType")}</SelectItem>
                  <SelectItem value="PRESCRIPTION">{t("recordType.PRESCRIPTION")}</SelectItem>
                  <SelectItem value="LAB_REPORT">{t("recordType.LAB_REPORT")}</SelectItem>
                  <SelectItem value="DOCTOR_VISIT">{t("recordType.DOCTOR_VISIT")}</SelectItem>
                  <SelectItem value="DISCHARGE_SUMMARY">{t("recordType.DISCHARGE_SUMMARY")}</SelectItem>
                  <SelectItem value="VACCINATION">{t("recordType.VACCINATION")}</SelectItem>
                  <SelectItem value="IMAGING">{t("recordType.IMAGING")}</SelectItem>
                  <SelectItem value="OTHER">{t("recordType.OTHER")}</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="recordDate">{t("upload.recordDateLabel")}</Label>
              <Input
                id="recordDate"
                type="date"
                value={recordDate}
                onChange={(event) => setRecordDate(event.target.value)}
                max={new Date().toISOString().slice(0, 10)}
              />
            </div>
          </div>

          <Button type="button" size="lg" className="w-full" onClick={handleSubmit} disabled={!file && !sampleKey}>
            <Sparkles aria-hidden="true" />
            {t("upload.process")}
          </Button>
        </CardContent>
      </Card>

      {/* Demo shortcuts — clearly labelled so nobody mistakes them for a real read. */}
      <Card className="border-dashed">
        <CardContent className="space-y-3">
          <div>
            <h2 className="flex items-center gap-2 font-semibold text-ink-900">
              <Sparkles className="size-5 text-brand-600" aria-hidden="true" />
              {t("landing.tryDemo")}
            </h2>
            <p className="mt-1 text-sm text-muted">
              {t("disclaimer.demoNote")}
            </p>
          </div>
          <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
            {SAMPLES.map((sample) => (
              <Button
                key={sample.key}
                type="button"
                variant={sampleKey === sample.key ? "primary" : "secondary"}
                onClick={() => {
                  setSampleKey(sample.key);
                  setFile(null);
                  setError(null);
                }}
                className="justify-start"
                aria-pressed={sampleKey === sample.key}
              >
                <span aria-hidden="true">{sample.emoji}</span>
                <span className="truncate text-sm">{t(sample.labelKey)}</span>
              </Button>
            ))}
          </div>
          {sampleKey && (
            <p className="text-sm text-brand-700">
              {t("upload.fileReady")}: {sampleKey} — {t("upload.processing")}
            </p>
          )}
        </CardContent>
      </Card>

      {easyRead && <p className="text-sm text-muted">{t("upload.hintSize")}</p>}
    </div>
  );
}
