-- Initial schema for Personal Health Copilot (SQLite).
-- Mirrors prisma/schema.prisma. Generated by hand because the sandbox could not download
-- Prisma's schema engine; `prisma migrate dev` on a networked machine will confirm no drift.

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "abhaNumber" TEXT,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "isDemo" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "HealthProfile" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "dateOfBirth" DATETIME,
    "relationship" TEXT NOT NULL DEFAULT 'SELF',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HealthProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "HealthRecord" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "profileId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'SAVED',
    "title" TEXT NOT NULL,
    "recordDate" DATETIME NOT NULL,
    "doctorName" TEXT,
    "facility" TEXT,
    "fileKey" TEXT,
    "fileName" TEXT,
    "mimeType" TEXT,
    "rawText" TEXT,
    "extractedJson" TEXT,
    "summary" TEXT,
    "ocrProvider" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "HealthRecord_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "HealthProfile" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "LabResult" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "healthRecordId" TEXT NOT NULL,
    "testName" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "numericValue" REAL,
    "unit" TEXT,
    "referenceRange" TEXT,
    "flag" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "metricName" TEXT,
    "date" DATETIME NOT NULL,
    CONSTRAINT "LabResult_healthRecordId_fkey" FOREIGN KEY ("healthRecordId") REFERENCES "HealthRecord" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Medication" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "profileId" TEXT NOT NULL,
    "sourceRecordId" TEXT,
    "name" TEXT NOT NULL,
    "dosage" TEXT NOT NULL,
    "frequency" TEXT NOT NULL,
    "timesPerDay" INTEGER NOT NULL DEFAULT 1,
    "durationDays" INTEGER,
    "startDate" DATETIME NOT NULL,
    "endDate" DATETIME,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Medication_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "HealthProfile" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Medication_sourceRecordId_fkey" FOREIGN KEY ("sourceRecordId") REFERENCES "HealthRecord" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "DoseLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "medicationId" TEXT NOT NULL,
    "doseDate" DATETIME NOT NULL,
    "slot" TEXT NOT NULL,
    "takenAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DoseLog_medicationId_fkey" FOREIGN KEY ("medicationId") REFERENCES "Medication" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "HealthMetric" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "profileId" TEXT NOT NULL,
    "metricName" TEXT NOT NULL,
    "value" REAL NOT NULL,
    "unit" TEXT NOT NULL,
    "recordedAt" DATETIME NOT NULL,
    "sourceRecordId" TEXT,
    "referenceLow" REAL,
    "referenceHigh" REAL,
    CONSTRAINT "HealthMetric_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "HealthProfile" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "HealthMetric_sourceRecordId_fkey" FOREIGN KEY ("sourceRecordId") REFERENCES "HealthRecord" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "DrugInteraction" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "medicineA" TEXT NOT NULL,
    "medicineB" TEXT NOT NULL,
    "severity" TEXT NOT NULL DEFAULT 'potential',
    "description" TEXT NOT NULL,
    "source" TEXT NOT NULL DEFAULT 'mock-demo-dataset'
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE INDEX "HealthProfile_userId_idx" ON "HealthProfile"("userId");

-- CreateIndex
CREATE INDEX "HealthRecord_profileId_recordDate_idx" ON "HealthRecord"("profileId", "recordDate");

-- CreateIndex
CREATE INDEX "LabResult_healthRecordId_idx" ON "LabResult"("healthRecordId");

-- CreateIndex
CREATE INDEX "Medication_profileId_idx" ON "Medication"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "DoseLog_medicationId_doseDate_slot_key" ON "DoseLog"("medicationId", "doseDate", "slot");

-- CreateIndex
CREATE INDEX "HealthMetric_profileId_metricName_recordedAt_idx" ON "HealthMetric"("profileId", "metricName", "recordedAt");

-- CreateIndex
CREATE UNIQUE INDEX "DrugInteraction_medicineA_medicineB_key" ON "DrugInteraction"("medicineA", "medicineB");
